### ISSUE TITLE
Solves in reverse order

### ISSUE THREAD

**Issue by MelvinSnijders** [eduherminio/AoCHelper#140]
Using `Solver.SolveAll();` will result in a reverse order, and somehow a duplicate being printed, as seen below:

![](https://i.imgur.com/qj4BNnl.png)

This is my folder structure:

![](https://i.imgur.com/cqEAVRp.png)

It looks like this issue is related to #137, but I'm not sure why this happens in my case.

**Comment by eduherminio** [comment]
Hi Melvin,

Thanks for suing `AoCHelper` and raising the issue.

The reverse order problem has indeed to do with the other issue you pointed out. Based pure observation, types were returned ordered by `FullName` when invoking `System.Reflection.Assembly.GetTypes()`, but apparently that's not the case when one has `_` symbols in them, and that's your case. I'll make sure to explicitly order them so that you get them in the right order.

Your repository also uncovered another issue: `AoCHelper` doesn't handle correctly exceptions in the constructors, with such exceptions making the `Solve`/`SolveAll` methods crash. I'll also look into that.

Regarding that duplicate being printed, I need to look deeper into that since it involves [`Spectre Console`](https://github.com/spectreconsole/spectre.console). It brings back some ghosts from v0.x when `Spectre Console` didn't support [Live display](https://spectreconsole.net/live/).

**Comment by eduherminio** [comment]
@MelvinSnijders Could you please test [v2.0.2-alpha.1](https://www.nuget.org/packages/AoCHelper/2.0.2-alpha.1) version and verify that both the ordering issue and the construction exceptions one are fixed?

I'll track the double rendering issue separately in #143.

**Comment by MelvinSnijders** [comment]
Just tested it, works great, thanks!

**Comment by eduherminio** [comment]
Awesome to read!
I'll try to look into the other issue, but if I don't immediately solve it I'll just release a non alpha version for these ones (v2.0.2) in the following days.
