### ISSUE TITLE
[Enhancement] Allow for higher resolution timings

### ISSUE THREAD

**Issue by tslater2006** [eduherminio/AoCHelper#30]
Should be able to leverage Stopwatch's "ElapsedTicks" and TimeSpan.TicksPerMillisecond to get partial millisecond timings:

![image](https://user-images.githubusercontent.com/1731714/101023592-98a01200-3538-11eb-85ab-3c95a1f7c76f.png)

**Comment by eduherminio** [comment]
The problem is that this 'quick and dirty' way of measuring the performance will never be reliable.
If you run `SolveAll()` or `Solve<T>()` multiple times, you'll get different results for each run, even when you do it in a GitHub Action (using 'someone' else's computer).

Given that, how useful is to have such a good resolution (partial milliseconds) if you are potentially getting a +-3ms difference between runs?
IMHO not much, and that's why `Elapsed time` should always be taken with a pinch of salt and I didn't originally implemented it using those elapsed ticks.

Tools such as [BenchmarkDotnet](https://benchmarkdotnet.org/) should be used if you really want to get into performance details, and even those measurements end up depending on the state of your machine when you run them. That's definitely the way to go if you want reliable performance information, which of course is not as fast to get as using the good old `Stopwatch`.
[I'm using it myself in this year's code](https://github.com/eduherminio/AoC2020/tree/main/src/AoC_2020.Benchmarks) to compare different implementations/solution for the same problem, in case you want to have a look.

**Comment by tslater2006** [comment]
Elapsed milliseconds (instead of ticks) does exactly what the enchancement is suggesting, however it returns a long instead of double. so you lose some precision. Its not like going off of ticks and dividing by TicksPerMillisecond is *less* reliable than what AoCHelper is using now. They are both sourced off the same info. 

![image](https://user-images.githubusercontent.com/1731714/101042393-c38f6380-3542-11eb-93e3-a2b7dedd0575.png)
https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System/services/monitoring/system/diagnosticts/Stopwatch.cs#L124

That said, the suggestion was born out of wanting to see if an alternate algorithm was faster for Day 2/3, and having it show a runtime of 0ms wasn't helping determine that. Seeing 0.09 and 0.01 certainly did. So maybe, what if the milliseconds are < some amount (5?, 10?) then show the partial, but for longer runtimes as the days progress it becomes less useful so elapsed milliseconds would be sufficient.

**Comment by eduherminio** [comment]
You raised a very good point about lower and higher amounts, I'll give it a proper thought and come back with some kind of proposal that involves more resolution for, at the very least, those 0ms solutions.
From 10ms, or even less, decimals equals to noise to me; but let me properly consider it.

**Comment by eduherminio** [comment]
**Option 1**  ➡️  2 decimal digits when **<10 ms**
![less_than_10](https://user-images.githubusercontent.com/11148519/101068380-f5cbb000-3598-11eb-936b-b21d3bb4dcff.PNG)

**Option 2**  ➡️ 2 decimal digits when **<1ms**
![less_than_1](https://user-images.githubusercontent.com/11148519/101068261-c74dd500-3598-11eb-8a7a-b2ec37f28077.PNG)

Both would solve the problem of 0ms solutions and, by using ticks everywhere as suggested, would help getting rid of some errors when rounding.

Option 2 seems clearer to me, because of the 'decimal digit noise' mixed with the variability.
However, I acknwledge that that's a personal preference. 

I'll make Option 2 the default configuration, and add an option to override the default milliseconds format specifier, so that you can do `Solver.MillisecondsFormatSpecifier = "F2";` and get two decimal digits everywhere, or any other possible formatting achievable via [standard numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings).

How does that sound, @tslater2006?

**Comment by tslater2006** [comment]
Sounds good to me! Thanks for considering the request 👍

**Comment by eduherminio** [comment]
[v0.12.1](https://github.com/eduherminio/AoCHelper/releases/tag/v0.12.1) released, including this enhancement.
